### PR TITLE
Filter Functionality

### PR DESCRIPTION
**Pull request by anandsr21harshit**
- Added Filter Bar
- User can now filter videos based on category

image

### CODE REVIEW

**Review by thegeorgenikhil — COMMENTED** [review]
Wouldn't there be conflicts if there are more than two contexts if you are using state and dispatch as the variable names? Not sure about this just asking.

**Review by thegeorgenikhil — COMMENTED** [review]
Better to name `dataReducer` or similar naming instead of reducer for better understanding
in reducer.js file

**Review by thegeorgenikhil — COMMENTED** [review]
Good to merge from my side, made some suggestions.
Would have liked a deployed link for preview.

**Review by thegeorgenikhil — APPROVED** [review]

**Comment by sushmita12345** [comment]
- UI looks good.
- Code is easily understandable.
- Go with above suggestion to replace the name Reducer name.
- No breakpoints, you can proceed to merge.

**Review by sushmita12345 — APPROVED** [review]

**Comment by anandsr21harshit** [comment]
Made changes as suggested

**Pull request merged**
